name: Docker Compose CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and run with Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
          
      - name: Tag and push image to Docker Hub
        run: |
          docker tag movie-recommender_flask-api ${{ secrets.DOCKER_USERNAME }}/movie-recommender:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/movie-recommender:latest


